[project]
name = "birefnet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch==2.13.0",
    "torchvision",
    "timm",
    "einops",
    "kornia",
    "huggingface-hub>0.25",
    "opencv-python",
    "pillow",
    "numpy<2",
]

[tool.uv]
exclude-newer-package = { torch = "2026-07-10", torchvision = "2026-07-10" }
